name: flutter_base
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  injectable: ^2.3.0
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.1.0
  firebase_remote_config: ^4.2.5
  firebase_analytics: ^10.4.5
  firebase_messaging:
  flutter_local_notifications:
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  # Route
  auto_route: ^7.8.4
  flutter_screenutil: ^5.9.0

  cloud_firestore: ^4.9.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  appsflyer_sdk: ^6.11.3
  change_app_package_name: ^1.1.0
  logger: ^2.0.2+1
  url_launcher: ^6.1.12
  share_plus: ^7.1.0
  package_info_plus: ^4.2.0
  shimmer: ^3.0.0
  easy_ads_flutter:
    git:
      #  url: https://bitbucket.org/innofyapp/flutter_ads.git
     url: https://KyLQ@bitbucket.org/innofyapp/flutter_ads.git
  device_info_plus: ^9.0.3
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  applovin_max: '3.3.0'
  upgrader: ^8.2.0
  permission_handler: ^11.0.1
  in_app_review: ^2.0.8
  lottie: ^2.7.0
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  battery_plus: ^5.0.2
  uuid: ^4.2.2
  google_maps_flutter_android: ^2.6.2
  pin_code_fields: ^8.0.1
  geocoding: ^2.1.1
  flutter_spinkit: ^5.2.0
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.4
  isar: ^3.1.0+1
  http: ^1.1.0
  cached_network_image: ^3.3.1
  dotted_border: ^2.1.0
  carousel_slider: ^4.2.1
  flutter_iap:
    git:
      url: https://bitbucket.org/innofyapp/flutter_iap.git
  map_launcher: ^3.1.0
  flutter_polyline_points: ^2.0.0
  flutter_lifecycle_detector: ^0.0.6
  flutter_activity_recognition: ^3.0.0
  pedometer: ^4.0.1
  tutorial_coach_mark: ^1.2.11
  marquee: ^2.2.3
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  build_runner:
  injectable_generator:
  auto_route_generator:
  flutter_lints: ^3.0.1
  flutter_gen_runner: ^5.3.1
  # Flavor
  flutter_flavorizr: ^2.2.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/icons/
    - assets/icons/places/
    - assets/icons/rates/
    - assets/icons/premium/
    - assets/icons/activity/
    - assets/images/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/languages/
    - assets/images/avatars/
    - assets/images/avatars/female/
    - assets/images/avatars/male/
    - assets/images/avatars/groups/
    - assets/images/markers/
    - assets/images/map_types/
    - assets/images/chat/
    - assets/ad_unit_id/dev/
    - assets/ad_unit_id/prod/
    - .env
    - .env.dev
    - .env.prod

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

#generate
flutter_gen:
  output: lib/src/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: MyColors

  assets:
    outputs:
      class_name: Assets
